project:
  type: website
  pre-render:
    - Rscript scripts/make_bill_pages.R
    - Rscript scripts/make_senator_pages.R

website:
  title: "UC Merced CA Legislative Simulation -- 2025"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Bills
        href: bills.qmd
      - text: Senators
        href: senators.qmd
      - text: Votes
        href: votes.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




