project:
  type: website
  output-dir: docs

website:
  title: "UC Merced CA Legislative Simulation -- 2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - bills.qmd
      - senators.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



