project:
  type: website
  pre-render:
    - Rscript scripts/make_bill_pages.R
    - Rscript scripts/make_senator_pages.R
    - Rscript scripts/make_lobby_pages.R
  

resources:
  - "files/"

website:
  title: "UC Merced CA Legislative Simulation -- 2025"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Bills
        href: bills.qmd
      - text: Senators
        href: senators.qmd
      - text: Votes
        href: votes.qmd
      - text: Districts
        href: map.qmd
      - text: Agendas
        href: agendas.qmd
      - text: Lobby
        href: lobby.qmd
      - text: News
        href: news.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




