project:
  type: website
  output-dir: docs
  pre-render:
    - Rscript scripts/make_bill_pages.R

website:
  title: "UC Merced CA Legislative Simulation -- 2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - bills.qmd
      - senators.qmd
      - text: Votes
        href: votes.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



