name: Quarto Publish (Hourly)

on:
  schedule:
    - cron: "0 * * * *"   # every hour at minute 0 (UTC)
  workflow_dispatch: {}
  push:
    branches: [ main, master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R deps (auto)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::readr
            any::dplyr
            any::gt
            any::janitor
            any::readxl
            any::knitr
            any::rmarkdown

      - name: Render site
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
