name: Quarto Publish (Hourly)

on:
  schedule:
    - cron: "0 * * * *"   # every hour at minute 0 (UTC)
  workflow_dispatch: {}
  push:
    branches: [ main, master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/R
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: ${{ runner.os }}-r-

      - name: Install R packages
        run: |
          R -q -e "req <- c('readr','dplyr','gt','janitor', 'readxl'); inst <- req[!req %in% installed.packages()[,'Package']]; if(length(inst)) install.packages(inst)"

      - name: Render site
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
